//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        public decimal ID_ACTIVIDAD { get; set; }
        public string DESC_ACTIVIDAD { get; set; }
        public System.DateTime FECHA_REALIZACION_ACT { get; set; }
        public Nullable<decimal> MONTO_RECAUDADO { get; set; }
        public string ACTIVO { get; set; }
        public decimal ID_TIPO_ACTIVIDAD { get; set; }
        public decimal ID_CONTRATO { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual TIPO_ACTIVIDAD TIPO_ACTIVIDAD { get; set; }
    }
}
