//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public decimal NUMRUT_CLI { get; set; }
        public string DRUT_CLI { get; set; }
        public string NOMBRE_CLIE { get; set; }
        public string APELLIDO_PAT_CLI { get; set; }
        public string APELLIDO_MAT_CLI { get; set; }
        public string MAIL_CLI { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<decimal> ID_USR { get; set; }
        public string DIRECCION_CLI { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO_CLI { get; set; }
        public string FONO_CLI { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual ICollection<CUENTA> CUENTA { get; set; }
    }
}
