//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.ACTIVIDAD = new HashSet<ACTIVIDAD>();
            this.CONTRATO_PAQUETE = new HashSet<CONTRATO_PAQUETE>();
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public decimal ID_CONTRATO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public decimal META { get; set; }
        public Nullable<decimal> MONTO_RESERVA { get; set; }
        public string ESTADO { get; set; }
        public decimal NUMRUT_EMP { get; set; }
        public decimal NUMRUT_CLI_TITULAR { get; set; }
    
        public virtual ICollection<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
        public virtual ICollection<CUENTA> CUENTA { get; set; }
    }
}
