//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public CUENTA()
        {
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }
    
        public decimal ID_CUENTA { get; set; }
        public decimal SALDO { get; set; }
        public decimal ID_CONTRATO { get; set; }
        public decimal NUMRUT_CLI { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
    }
}
