//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public decimal ID_DOCUMENTO { get; set; }
        public string URL_DOCUMENTO { get; set; }
        public decimal ID_CONTRATO { get; set; }
        public decimal ID_PAQUETEVIAJE { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public System.DateTime FECHA_SUBIDA_DOC { get; set; }
        public string DESC_DOCUMENTO { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual CONTRATO_PAQUETE CONTRATO_PAQUETE { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
