//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public decimal NUMRUT_EMP { get; set; }
        public string DRUT_EMP { get; set; }
        public string NOMBRE_EMP { get; set; }
        public string APELLIDO_PAT_EMP { get; set; }
        public string APELLIDO_MAT_EMP { get; set; }
        public string MAIL_LABORAL { get; set; }
        public string DIRECCION_EMP { get; set; }
        public string ACTIVO { get; set; }
        public decimal ID_USR { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO_EMP { get; set; }
        public string FONO_EMP { get; set; }
    
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
