//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAQUETEVIAJE
    {
        public PAQUETEVIAJE()
        {
            this.CONTRATO_PAQUETE = new HashSet<CONTRATO_PAQUETE>();
            this.SERVICIO_PAQUETE = new HashSet<SERVICIO_PAQUETE>();
        }
    
        public decimal ID_PAQUETEVIAJE { get; set; }
        public string DESC_PAQUETEVIAJE { get; set; }
        public decimal VALOR_PAQUETEVIAJE { get; set; }
        public string ACTIVO { get; set; }
        public System.DateTime FECHA_CREACION_PAQVIAJE { get; set; }
    
        public virtual ICollection<CONTRATO_PAQUETE> CONTRATO_PAQUETE { get; set; }
        public virtual ICollection<SERVICIO_PAQUETE> SERVICIO_PAQUETE { get; set; }
    }
}
