//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_TRANSACCION
    {
        public TIPO_TRANSACCION()
        {
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }
    
        public decimal ID_TIPO_TRANSACCION { get; set; }
        public string DESC_TRANSACCION { get; set; }
    
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
    }
}
