//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public decimal ID_TRANSACCION { get; set; }
        public System.DateTime FECHA_TRANSACCION { get; set; }
        public decimal MONTO_TRANSACCION { get; set; }
        public decimal ID_CUENTA { get; set; }
        public decimal ID_TIPO_TRANSACCION { get; set; }
        public string ACTIVO { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
        public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
    }
}
